project_name: cgapp
env_files:
  github_token: ~/.goreleaser/github_token

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    targets:
      - linux_amd64
      - darwin_amd64
      - windows_amd64
    env:
      - CGO_ENABLED=0

dockers:
  # You can have multiple Docker images.
  - # GOOS of the built binary that should be used.
    goos: linux
    goarch: amd64

    # Templates of the Docker image names.
    image_templates:
      - "koddr/cgapp:latest"
      - "koddr/cgapp:{{ .Tag }}"
      - "koddr/cgapp:{{ .Tag }}-{{ .Env.GO_VERSION }}"
      - "koddr/cgapp:v{{ .Major }}"

    skip_push: true

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    extra_files:
      - dist/cgapp_linux_amd64/cgapp

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOSs.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
