project_name: cgapp
env_files:
  github_token: ~/.goreleaser/github_token

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    targets:
      - linux_amd64
      - darwin_amd64
      - windows_amd64
    env:
      - CGO_ENABLED=0

dockers:
  - # GOOS of the built binary that should be used.
    goos: linux
    goarch: amd64

    # Name templates of the built binaries that should be used.
    binaries:
      - cgapp

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # skip_push: true

    # Templates of the Docker image names.
    image_templates:
      - "koddr/cgapp:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "koddr/cgapp:{{ .Major }}.{{ .Minor }}"
      - "koddr/cgapp:{{ .Major }}"
      - "koddr/cgapp:latest"

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
