version: "2"

vars:
  APP: cgapp{{exeExt}}

tasks:
  default:
    cmds:
      - task: build

  security:
    desc: Run gosec for project
    cmds:
      - gosec -quiet ./...

  generate:
    desc: Generate blob.go with embed files
    cmds:
      - go generate ./...

  test:
    desc: Test project
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  build:
    desc: Test release CLI
    cmds:
      - task: generate
      - task: security
      - task: test
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    desc: Install CLI to $GOPATH/bin
    cmds:
      - task: generate
      - task: security
      - task: test
      - go build -i -o $GOPATH/bin/cgapp ./*.go

  release:
    desc: GitHub release for CLI
    cmds:
      - task: generate
      - task: security
      - task: test
      - git tag -a {{.VERSION}} -m "{{.VERSION}}"
      - goreleaser --snapshot --skip-publish --rm-dist

  delete-tag:
    desc: Delete git tag (version)
    cmds:
      - git tag --delete {{.VERSION}}

  update-pkg-cache:
    desc: Update pkg.go.dev cache for a new version
    cmds:
      - curl -i https://proxy.golang.org/github.com/create-go-app/cli/@v/{{.VERSION}}.info
