version: "3.7"

services:
  static:
    container_name: static
    build:
      context: ./frontend

  app:
    container_name: app
    build:
      context: ./backend
    networks:
      nginx_net:
    restart: always

networks:
  nginx_net:
    external: true
