version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - static:/frontend/build

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - static:/frontend/build
    restart: always
    depends_on:
      - frontend

volumes:
  static:
