# Ansible role for deploy the PostgreSQL for the Create Go App project.
# Author: Vic Shóstak <vic@shostak.dev> (https://shostak.dev)
# For more information, please visit https://create-go.app/

---
#
# Create folder for PostgreSQL database.
#
- name: Ensures PostgreSQL dir exists
  file:
    state: directory
    path: "{{ server_dir }}/database"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"

#
# Run official PostgreSQL Docker container with specified version.
#
- name: Run PostgreSQL container
  docker_container:
    name: cgapp-postgres
    image: "postgres:{{ postgres_version }}"
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "{{ postgres_port }}:{{ postgres_port }}"
    volumes:
      - "{{ server_dir }}/database/data/:/var/lib/postgresql/data"
