# Ansible playbook for deploy the Create Go App project.
# Author: Vic Shóstak <truewebartisans@gmail.com> (https://1wa.co)
# For more information, please visit https://create-go.app/

---
- hosts: "{{ host }}"
  become: yes

  roles:
    # Build & run project's backend
    - deploy/cgapp_backend
    # Configure and run project's webserver
    - deploy/cgapp_webserver
    # Configure and run project's database
    - deploy/cgapp_database
