# deploy-playbook.yml by Vic Shóstak <truewebartisans@gmail.com> (https://1wa.co)

---
- hosts: "{{ host }}"
  become: yes

  roles:
    # Build & run project's frontend
    - deploy/cgapp_frontend
    # Build & run project's backend
    - deploy/cgapp_backend
    # Configure and run project's webserver
    - deploy/cgapp_webserver
    # Configure and run project's database
    - deploy/cgapp_database
