# Ansible playbook for deploy the Create Go App project.
# Author: Vic Shóstak <vic@shostak.dev> (https://shostak.dev)
# For more information, please visit https://create-go.app/

---
- hosts: "{{ host }}"
  become: yes

  tasks:
    #
    # Create a new Docker network for connect all project elements into one network.
    #
    - name: Create a new Docker network ({{ network_name }})
      docker_network:
        name: "{{ network_name }}"

    #
    # Check all necessary project folders for future use.
    #
    - name: Check, if ./backend directory is exists
      stat:
        path: ./backend
      register: backend_folder

    - name: Check, if ./webserver directory is exists
      stat:
        path: ./webserver
      register: webserver_folder

    #
    # The block that builds and runs the backend part of the project.
    #
    - name: Backend block
      block:
        - name: Builds Docker image for backend
          docker_image:
            name: cgapp_backend # name of the backend image
            build:
              path: ./backend # folder with Dockerfile
              pull: yes
            source: build

        - name: Runs Docker container with backend
          docker_container:
            name: cgapp-backend # name of the backend container
            image: cgapp_backend:latest
            recreate: yes
            networks:
              - name: "{{ network_name }}"
            ports:
              - "{{ backend_port }}:{{ backend_port }}"
            state: started
      # Run block only if ./backend is a folder and exists.
      when: backend_folder.stat.exists and backend_folder.stat.isdir

    #
    # The block that builds and runs the webserver part of the project.
    #
    - name: Webserver block
      block:
        - name: Builds Docker image for webserver
          docker_image:
            name: cgapp_webserver # name of the webserver image
            build:
              path: ./webserver
              pull: yes
            source: build

        - name: Runs Docker container with webserver
          docker_container:
            name: cgapp-webserver # name of the webserver container
            image: cgapp_webserver:latest
            recreate: yes
            networks:
              - name: "{{ network_name }}"
            env:
              APP_DOMAIN: "{{ host }}"
            ports:
              - "80:80"
            state: started
      # Run block only if ./webserver is a folder and exists.
      when: webserver_folder.stat.exists and webserver_folder.stat.isdir
